### ISSUE TITLE
Compatibility with Binary-Frame GEVI Data

### ISSUE THREAD

**Issue by kurtulusbulus** [NICALab/SUPPORT#13]
Hello,

Thank you for the efforts in creating and sharing this pipeline; it's an impressive project.

I'm interested in applying this pipeline to our dataset recorded with a GEVI and an ultra-high frame rate camera. However, the camera we use produces binary frames. I couldn't find any information regarding the required bit depth of the input images for the AI model in the paper. I'm wondering if it's possible to use a dataset comprised of a series of binary images. From the paper and the documentation, I can understand that this model can be trained with our own dataset by using the traning GUI, but I still wanted to get your opinion before this. 

Thank you in advance for your assistance.

Best regards,
Kurtulus

**Comment by EOMMINHO** [comment]
Hi Kurtulus,

Thank you for your interest in our denoising algorithm.

Are you asking if your data is binary, similar to what is obtained from event cameras or DVS?
I think the algorithm could work with those kinds of data since our algorithm does not have strict restrictions on the bit depth of the input images. 

That said, due to the unique nature of binary data compared to traditional camera data, you might need to adjust the hyperparameters significantly from our standard settings for optimal results. If you're interested, we're open to running a preliminary test using a sample of your data to see how well it performs.

Best regards,
Minho

**Comment by EOMMINHO** [comment]
Hi Kurtulus,

Thank you for your interest in our denoising algorithm.

I think the algorithm could work with those kinds of data since our algorithm does not have strict restrictions on the bit depth of the input images.

That said, due to the unique nature of binary data compared to traditional camera data, you might need to adjust the hyperparameters significantly from our standard settings for optimal results. If you're interested, we're open to running a preliminary test using a sample of your data to see how well it performs.

Best regards,
Minho
