### ISSUE TITLE
Train GUI missing is_rotate

### ISSUE THREAD

**Issue by saglag** [NICALab/SUPPORT#5]
Running the GUI for training ran into the following issue:

Traceback (most recent call last):
  File "/home/doug/python_projects/support_dir/SUPPORT/src/GUI/train_GUI.py", line 242, in run
    noisy_image, _ = random_transform(noisy_image, None, rng)
TypeError: random_transform() missing 1 required positional argument: 'is_rotate'
Aborted (core dumped)

https://github.com/NICALab/SUPPORT/blob/b4760b3eed68bd53778957a095ea03405d87ce53/src/GUI/train_GUI.py#L242

Line 242 of train_GUI.py is missing the is_rotate argument. I inserted into line 229 
is_rotate = True if self.parent.model.bs_size[0] == self.parent.model.bs_size[1] else False
to specify it prior to training to match the train.py command line interface script. 

Following this, the GUI for training runs as expected.

**Comment by SteveJayH** [comment]
Thanks! I modified data augmentation function to turn on and off the rotation recently.
That part is for rectangular blind spot rather than square. Since current train_GUI only supports square blind spot (`is_rotate` will currently always `True`), and I think default `is_rotate` might be `True` so I changed the default value of `is_rotate` as `True` in `random_transform` function.

`def random_transform(input, target, rng, is_rotate):`

-->

`def random_transform(input, target, rng, is_rotate=True):`

I also checked that train_GUI runs well after this modification.

Thanks for checking!
